(require 'files)
(let ((default-directory user-emacs-directory))
  (load-file "early-init.el")
  (load-file "init.el"))
(let ((default-directory (expand-file-name "tests" user-emacs-directory)))
  (mapcar 'load-file (directory-files default-directory nil ".*-tests\.el")))
(ert-run-tests-batch-and-exit (getenv "EMACS_TEST_REGEX"))
